---

- name: iptables install
  yum:
    pkg: iptables
  when: ansible_os_family == "RedHat"

- name: iptables install
  yum:
    pkg: iptables-services
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: removing firewalld
  yum:
    pkg:
      - firewalld
      - firewalld-filesystem
      - python-firewall
    state: absent
  when: ansible_os_family == "RedHat"

- name: enable iptables
  service:
    name: iptables
    enabled: yes

- name: deploying host dependend rules
  template:
    src: '{{ iptables_template }}'
    dest: /etc/sysconfig/iptables
  notify: reload iptables
  when: ansible_os_family == "RedHat"

...
